
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from server import *

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)




root = Tk()
root.title('Giá Vàng')
root.geometry("1199x910")
#root.configure(bg = "#A9C1C0")

window0 = Frame(root)
window0.grid(row=0, column=0, sticky='news')


def runServer():
    nClient = 0
    while(nClient<10):       
        try:
            global server
            server, clientAdd =soc.accept()
            #threading.Thread(target=lambda: updateDataEvery30Min()).start()
            #handleClient(server,clientAdd)
            global thr
            thr = threading.Thread(target=handleClient, args=(server,clientAdd))
            thr.daemon = False
            thr.start()
            # if(soc.close()==True):
            #     thr.stop()
            #     thr.join()
        except: #Bắt trường hợp client đóng kết nối đột ngột
            soc.close()
            break
            print("Error")
        nClient+=1

    print("End server")

    #soc.close()

thr2= threading.Thread(target=lambda: runServer())
thr2.start()



bg0=PhotoImage(file=relative_to_assets("serverMenu.png"))
label_0=Label(window0,image=bg0)
label_0.pack(expand=True,fill=BOTH)

textBox = Label(window0,text=hostAdd, font="Times 22", background="#cbdad9",)
textBox.place(x=60,y=175)


textBox = Label(window0,text=hostPort, font="Times 22", background="#cbdad9",)
textBox.place(x=495,y=175)

def button1Fun():
    button_1.configure(state="disable")
    server.shutdown(socket.SHUT_RDWR)
    soc.close()
    print("close all")

button_image_1 = PhotoImage(
    file=relative_to_assets("Button.png"))
button_1 = Button(
    image=button_image_1,cursor="hand2", bg="#a9c1c0", activebackground="#a9c1c0",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: button1Fun(),
    relief="flat"
)
button_1.place(
    x=925,
    y=155,
    width=237.0,
    height=85.0
)


root.resizable(False, False)
root.mainloop()
server.shutdown(socket.SHUT_RDWR)
soc.close()